SET search_path TO tasks, public;

ALTER TABLE tareas ADD COLUMN IF NOT EXISTS lugar_nombre VARCHAR(120);
ALTER TABLE tareas ADD COLUMN IF NOT EXISTS lugar_direccion TEXT;
ALTER TABLE tareas ADD COLUMN IF NOT EXISTS place_id VARCHAR(120);
ALTER TABLE tareas ADD COLUMN IF NOT EXISTS lugar_lat DOUBLE PRECISION;
ALTER TABLE tareas ADD COLUMN IF NOT EXISTS lugar_lng DOUBLE PRECISION;